educator/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from api.views import TaskViewSet

router = DefaultRouter()
router.register(r'tasks', TaskViewSet, basename='tasks')

urlpatterns = [
    path('', include(router.urls)),
    # path('auth/', include('djoser.urls.authtoken')),
]

educator/educator/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from educator import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task.urls', namespace='task')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('api/', include('api.urls')),
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    path('schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

educator/task/urls.py
from django.urls import path

from task.views import *

app_name = 'task'

urlpatterns = [
    path('', index, name='home'),
    path('categories/', category, name='category'),
    path('category/<int:category_id>/', category_detail, name='category_detail'),
    path('subject/', subject, name='subject'),
    path('subject/<int:subject_id>/', subject_detail, name='subject_detail'),
    path('task/<int:task_id>/', task_detail, name='task_detail'),
    path('search/', search_results, name='search'),
    path('toggle_like/<int:task_id>/', like_toggle, name='toggle_like'),
    path('load_more_comments/<int:task_id>/', load_more_comments, name='load_more_comments'),
    path('profile/<str:username>/', user_profile, name='profile'),
    path('task/create/', create_task, name='create_task'),
    path('task/edit/<int:task_id>/', edit_task, name='edit_task'),
    path('delete/<int:task_id>/', delete_task, name='delete_task'),
]

educator/task/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils import timezone

User = get_user_model()


class Task(models.Model):
    title = models.CharField(max_length=55, verbose_name='Задача')
    description = models.TextField(blank=True, verbose_name="Описание")
    code = models.TextField(blank=True, verbose_name="Python код")
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    time_update = models.DateTimeField(auto_now=True, verbose_name="Дата изменения")
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    is_published = models.BooleanField(default=True, verbose_name="Опубликовано")
    category = models.ForeignKey(
        'Category',
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="Категория",
        related_name='category'
    )
    subject = models.ForeignKey(
        'Subject',
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="Тема",
        related_name='subject'
    )
    # likes = models.ManyToManyField(User, related_name='liked_tasks', blank=True)
    # dislikes = models.ManyToManyField(User, related_name='disliked_tasks', blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('task_detail', kwargs={'task_id': self.pk})

    class Meta:
        verbose_name = 'Задачи'
        verbose_name_plural = 'Задачи'
        ordering = ['-pub_date', 'title']


class Category(models.Model):
    title = models.CharField(max_length=55, verbose_name='Категория')
    description = models.TextField(blank=True, verbose_name="Описание")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'category_id': self.pk})

    class Meta:
        verbose_name = 'Категории'
        verbose_name_plural = 'Категории'
        ordering = ['title']


class Subject(models.Model):
    title = models.CharField(max_length=55, verbose_name='Тема')
    description = models.TextField(blank=True, verbose_name="Описание")
    category = models.ForeignKey(
        'Category',
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="Категория",
        related_name='subject'
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('subject_detail', kwargs={'subject_id': self.pk})

    class Meta:
        verbose_name = 'Темы'
        verbose_name_plural = 'Темы'
        ordering = ['title']


class TaskImage(models.Model):
    image = models.ImageField(
        upload_to="photos/%Y/%m/%d/",
        verbose_name="Изображение",
        null=True,
    )
    task = models.ForeignKey(
        'Task',
        on_delete=models.CASCADE,
        null=True,
        verbose_name="Изображение",
        related_name='image',
    )

    class Meta:
        verbose_name = 'Изображения'
        verbose_name_plural = 'Изображения'
        ordering = ['task']


class Comment(models.Model):
    task = models.ForeignKey(
        'Task',
        on_delete=models.CASCADE,
        null=True,
        verbose_name="Комментарий",
        related_name='comment',
    )
    text = models.TextField(blank=True, verbose_name="Комментарий")
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
        default=1  # Здесь 1 - это ID существующего пользователя или другое значение по умолчанию
    )
    pub_date = models.DateTimeField(default=timezone.now, verbose_name="Дата публикации")
    time_update = models.DateTimeField(auto_now=True, verbose_name="Дата изменения")

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ['pub_date']


class Chat(models.Model):
    participants = models.ManyToManyField(User, related_name='chats')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Chat {self.id}"


class Message(models.Model):
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE, related_name='messages')
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Message from {self.sender} in Chat {self.chat.id}"


class Like(models.Model):
    user = models.ForeignKey(
        User,
        related_name='likes',
        verbose_name='Пользователь',
        on_delete=models.CASCADE
    )
    task = models.ForeignKey(
        Task,
        related_name='likes',
        verbose_name='Пост',
        on_delete=models.CASCADE
    )

    def __str__(self):
        return f"Like from {self.user} on post {self.task.title}"

educator/task/forms.py
from django import forms
from .models import *


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'code', 'category', 'subject']


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
        }

educator/task/views.py
import random

from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from django.views.decorators.http import require_POST
from django.utils.text import slugify
from django.http import JsonResponse, HttpResponseForbidden
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

from task.models import *
from task.forms import *

MENU = [{'title': 'О сайте', 'url_name': 'about'},
        {'title': 'Добавить статью', 'url_name': 'add_page'},
        {'title': 'Обратная связь', 'url_name': 'contact'},
        {'title': 'Войти', 'url_name': 'login'},
        ]
NUMBER_OF_CARDS = 9


def index(request):
    random_number = random.randint(1, 100000)
    tasks = Task.objects.all()
    categories = Category.objects.all()
    subjects = Subject.objects.all()
    paginator = Paginator(tasks, NUMBER_OF_CARDS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'title': 'Главная страница',
        'menu': MENU,
        'categories': categories,
        'subjects': subjects,
        'category_selected': 0,
        'random_number': random_number,
    }
    return render(request, 'task/index.html', context=context)


def category(request):
    task = Task.objects.all()
    categories = Category.objects.all()
    subjects = Subject.objects.all()
    paginator = Paginator(categories, NUMBER_OF_CARDS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'title': 'Главная страница',
        'menu': MENU,
        'task': task,
        'page_obj': page_obj,
        'subjects': subjects,
        'category_selected': 0,
    }
    return render(request, 'task/category.html', context)


def category_detail(request, category_id):
    categories = Category.objects.all()
    category = get_object_or_404(Category, id=category_id)
    category_subject = Subject.objects.filter(category=category)
    subjects = Subject.objects.all()
    paginator = Paginator(category_subject, NUMBER_OF_CARDS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'title': 'Детали категории',
        'categories': categories,
        'menu': MENU,
        'category': category,
        'page_obj': page_obj,
        'subjects': subjects,
    }
    return render(request, 'task/category_detail.html', context=context)


def subject(request):
    task = Task.objects.all()
    categories = Category.objects.all()
    subjects = Subject.objects.all()
    paginator = Paginator(subjects, NUMBER_OF_CARDS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'title': 'Главная страница',
        'menu': MENU,
        'task': task,
        'categories': categories,
        'page_obj': page_obj,
        'category_selected': 0,
    }
    return render(request, 'task/subject.html', context=context)


def subject_detail(request, subject_id):
    categories = Category.objects.all()
    subjects = Subject.objects.all()
    subject = get_object_or_404(Subject, pk=subject_id)
    tasks = Task.objects.filter(subject=subject_id)
    paginator = Paginator(tasks, NUMBER_OF_CARDS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'title': subject.title,
        'menu': MENU,
        'subject': subject,
        'page_obj': page_obj,
        'categories': categories,
        'subjects': subjects,
    }
    return render(request, 'task/subject_detail.html', context)


def task_detail(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    categories = Category.objects.all()
    subjects = Subject.objects.all()
    images = TaskImage.objects.filter(task=task_id)
    comments = Comment.objects.filter(task=task_id)
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.task = task
            new_comment.user = request.user
            new_comment.save()
            comment_form = CommentForm()
    else:
        comment_form = CommentForm()
    context = {
        'title': 'Главная страница',
        'menu': MENU,
        'task': task,
        'categories': categories,
        'subjects': subjects,
        'category_selected': 0,
        'images': images,
        'comments': comments,
        'comment_form': comment_form
    }
    return render(request, 'task/task_detail.html', context=context)


def search_results(request):
    query = request.GET.get('q')
    if query:
        tasks = Task.objects.filter(
            Q(title__icontains=query) | Q(description__icontains=query)
        )
        categories = Category.objects.filter(title__icontains=query)
        subjects = Subject.objects.filter(title__icontains=query)

        # Create separate lists for each model
        task_results = [{'model_name': 'task', 'object': task} for task in tasks]
        category_results = [{'model_name': 'category', 'object': category} for category in categories]
        subject_results = [{'model_name': 'subject', 'object': subject} for subject in subjects]

        # Combine the lists and sort by model name
        results = task_results + category_results + subject_results
        results.sort(key=lambda x: x['model_name'])

        # Преобразуем запрос в URL-совместимый формат
        slugified_query = slugify(query)
    else:
        results = []
        slugified_query = None
    context = {
        'results': results,
        'slugified_query': slugified_query
    }
    return render(request, 'task/search_results.html', context)


# def toggle_like(request, task_id):
#     task = get_object_or_404(Task, pk=task_id)
#     user = request.user
#
#     if user.is_authenticated:
#         if task.likes.filter(id=user.id).exists():
#             task.likes.remove(user)
#         else:
#             task.likes.add(user)
#
#     return JsonResponse({'likes_count': task.likes.count()})


def load_more_comments(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    comments = Comment.objects.filter(task=task).order_by('-pub_date')[10:]

    data = []
    for comment in comments:
        data.append({
            'author': comment.author.username,
            'text': comment.text,
            'pub_date': comment.pub_date.strftime("%d %B %Y, %H:%M")
        })

    return JsonResponse(data, safe=False)


@login_required
@require_POST
def like_toggle(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    user = request.user
    try:
        like = Like.objects.get(user=user, task=task)
        like.delete()
        liked = False
    except Like.DoesNotExist:
        Like.objects.create(user=user, task=task)
        liked = True
    like_count = task.likes.count()
    return JsonResponse({'liked': liked, 'like_count': like_count})


def user_profile(request, username):
    user = get_object_or_404(User, username=username)
    tasks = Task.objects.filter(author=user)
    # Проверяем, существует ли чат между текущим пользователем и пользователем профиля
    chat = Chat.objects.filter(participants=request.user).filter(participants=user).first()
    if not chat:
        chat = Chat.objects.create()
        chat.participants.add(request.user, user)
    paginator = Paginator(tasks, NUMBER_OF_CARDS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'user': user,
        'page_obj': page_obj,
        'chat': chat,
    }
    return render(request, 'task/profile.html', context)


@login_required
def create_task(request, task_id=None):
    if task_id is not None:
        task = get_object_or_404(Task, pk=task_id)
        if task.author != request.user:
            return HttpResponseForbidden("You don't have permission to edit this task.")
    else:
        task = None

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            task = form.save(commit=False)
            task.author = request.user
            task.save()
            return redirect('task:task_detail', task_id=task.pk)
    else:
        form = TaskForm(instance=task)

    context = {
        'form': form,
        'task': task,
    }
    return render(request, 'task/create_task.html', context)


def edit_task(request, task_id):
    task = get_object_or_404(Task, pk=task_id)

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect('task:task_detail', task_id=task_id)
    else:
        form = TaskForm(instance=task)

    return render(request, 'task/edit_task.html', {'form': form, 'task': task})


def delete_task(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    if request.method == 'POST':
        task.delete()
        return redirect('task:home')

    return render(request, 'task/delete_task.html', {'task': task})


@login_required
def chat_list(request):
    chats = Chat.objects.filter(participants=request.user)
    context = {
        'chats': chats
    }
    return render(request, 'task/chat_list.html', context)


@login_required
def chat_detail(request, chat_id):
    chat = get_object_or_404(Chat, id=chat_id)
    messages = Message.objects.filter(chat=chat)
    form = MessageForm()

    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data['content']
            sender = request.user
            message = Message.objects.create(chat=chat, sender=sender, content=content)

    context = {
        'chat': chat,
        'messages': messages,
        'form': form,
    }

educator/task/templates/task/includes/footer.html
<!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted">
    <!-- Section: Social media -->
    <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
        <!-- Left -->
        <div class="me-5 d-none d-lg-block">
            <span>Get connected with us on social networks:</span>
        </div>
        <!-- Left -->

        <!-- Right -->
        <div>
            <a href="https://www.linkedin.com/in/kirill-svitsov/" class="me-4 text-reset">
                <i class="fab fa-linkedin"></i>
            </a>
            <a href="https://github.com/Kirill-Svitsov" class="me-4 text-reset">
                <i class="fab fa-github"></i>
            </a>
        </div>
        <!-- Right -->
    </section>
    <!-- Section: Social media -->

    <!-- Section: Links  -->
    <section class="">
        <div class="container text-center text-md-start mt-5">
            <!-- Grid row -->
            <div class="row mt-3">
                <!-- Grid column -->
                <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                    <!-- Content -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        <i class="fas fa-gem me-3"></i>Kirill Svitsov
                    </h6>
                    <p>
                        This is my pet project to consolidate knowledge of Django.
                    </p>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        Products
                    </h6>
                    <p>
                        <a href="#!" class="text-reset">Python</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Django</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">JS</a>
                    </p>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        Useful links
                    </h6>
                    <p>
                        <a href="#!" class="text-reset">Settings</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Help</a>
                    </p>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
                    <p><i class="fas fa-home me-3"></i> Lisbon, Portugal</p>
                    <p>
                        <i class="fas fa-envelope me-3"></i>
                        svicovkirill@gmail.com
                    </p>
                    <p><i class="fas fa-phone me-3"></i> + 7 909 140 11 18</p>
                    <p><i class="fas fa-print me-3"></i> + 351 968 106 590</p>
                </div>
                <!-- Grid column -->
            </div>
            <!-- Grid row -->
        </div>
    </section>
    <!-- Section: Links  -->

    <!-- Copyright -->
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
        © {{ year }} Copyright
    </div>
    <!-- Copyright -->
</footer>
<!-- Footer -->

educator/task/templates/task/includes/header.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand neon-link-red" href="{% url 'task:home' %}">Educator</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="categoriesDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Категории
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="categoriesDropdown">
                        <li><a class="dropdown-item" href="{% url 'task:category' %}">Все категории</a></li>
                        {% for category in categories %}
                        <li><a class="dropdown-item" href="{% url 'task:category_detail' category_id=category.pk %}">
                            {{ category.title }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="subjectsDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Темы
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="subjectsDropdown">
                        <li><a class="dropdown-item" href="{% url 'task:subject' %}">Все темы</a></li>
                        {% for subject in subjects %}
                        <li><a class="dropdown-item" href="{% url 'task:subject_detail' subject_id=subject.pk %}">
                            {{ subject.title }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link neon-link-green" href="">Прочее</a>
                </li>
                {% if user.is_superuser %}
                <li class="nav-item">
                    <a class="nav-link neon-link-blue" href="{% url 'admin:index' %}">Админ панель</a>
                </li>
                {% endif %}
                {% with request.resolver_match.view_name as view_name %}
                <li class="nav-item">
                    <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}"
                       href="{% url 'about:author' %}">
                        Об авторе
                    </a>
                </li>
                {% endwith %}
                {% if request.user.is_authenticated %}
                    {% if request.user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                {{ request.user.username }}
                            </a>
                            <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                                <li>
                                    <a class="dropdown-item" href="{% url 'task:create_task' %}">
                                        Создать новую запись
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'task:profile' username=request.user.username %}">
                                        Перейти в профиль
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item {% if view_name  == 'users:password_change_form' %}active{% endif %}"
                                       href="{% url 'users:password_change_form' %}">
                                        Изменить пароль
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item {% if view_name  == 'users:logout' %}active{% endif %}"
                                       href="{% url 'users:logout' %}">
                                        Выйти
                                    </a>
                                </li>
                            </ul>
                        </li>
                    {% endif %}
                {% else %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            Для пользователя
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                            <li>
                                <a class="dropdown-item {% if view_name  == 'users:login' %}active{% endif %}"
                                   href="{% url 'users:login' %}">
                                    Войти
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item {% if view_name  == 'users:signup' %}active{% endif %}"
                                   href="{% url 'users:signup' %}">
                                    Регистрация
                                </a>
                            </li>
                        </ul>
                    </li>
                {% endif %}
            </ul>
            <form class="d-flex ms-auto" action="{% url 'task:search' %}" method="get">
                <input class="form-control me-2" type="search" name="q" placeholder="Поиск" aria-label="Поиск">
                <button class="btn btn-outline-success" type="submit">Поиск</button>
            </form>
        </div>
    </div>
</nav>


<!-- Добавляем ссылку на библиотеку jQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!-- Добавляем ссылку на библиотеку Bootstrap JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>

<script>
    $(document).ready(function () {
        // Добавляем скрипт для бургер-меню
        $('.navbar-toggler').click(function () {
            $('.navbar-collapse').toggleClass('show');
        });
    });
</script>

educator/task/templates/task/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                Предыдущая
            </a>
        </li>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
        <li class="page-item active">
            <span class="page-link">{{ i }}</span>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                Следующая
            </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
                Последняя
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}

educator/task/templates/task/includes/task_card.html
{% load static %}
<div class="col-12 col-md-6 col-xl-4 mb-4">
    <div class="card h-100 shadow">
        <div class="card-body">
            <h5 class="card-title">{{task.title}}</h5>
            <p class="card-text">{{task.description|linebreaks|truncatewords:20}}.</p>
            <div class="category-subject-links">
                <p>Категория: <a href="{% url 'task:category_detail' category_id=task.category.pk %}">
                    {{ task.category }}</a>
                </p>
            </div>
            <div class="category-subject-links">
                <p>Тема: <a href="{% url 'task:subject_detail' subject_id=task.subject.pk %}">
                    {{ task.subject }}</a>
                </p>
            </div>
            <a href="{% url 'task:task_detail' task_id=task.pk %}" class="btn btn-primary read-more-btn">Read
                entirely</a>
            <div class="author-date">
                <a href="{% url 'task:profile' username=task.author %}" class="author">{{ task.author }}</a>
                <span>{{task.time_update}}</span>
            </div>
        </div>
        <div class="card-footer">
            <div class="d-flex justify-content-between">
                <div class="like-dislike">
                    <button class="like-button" data-task-id="{{ task.id }}">
                        <i class="far fa-thumbs-up"></i>
                    </button>
                    <span class="likes-count">{{ task.likes.count }}</span>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
.like-button, .dislike-button {
    border: none;
    background: none;
    cursor: pointer;
    font-size: 1.5em; /* Размер иконки */
    color: #000; /* Цвет иконки */
}

.like-button:focus, .dislike-button:focus {
    outline: none;
}
.like-button i, .dislike-button i {
    border: none;
}
.like-button:hover i {
    color: #007bff; /* Голубой цвет для лайка */
}

.dislike-button:hover i {
    color: #ff6b6b; /* Бледно-красный цвет для дизлайка */
}
</style>