educator/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from api.views import TaskViewSet

router = DefaultRouter()
router.register(r'tasks', TaskViewSet, basename='tasks')

urlpatterns = [
    path('', include(router.urls)),
    # path('auth/', include('djoser.urls.authtoken')),
]

educator/educator/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from educator import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task.urls', namespace='task')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('api/', include('api.urls')),
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    path('schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

educator/task/urls.py
from django.urls import path

from task.views import *

app_name = 'task'

urlpatterns = [
    path('', index, name='home'),
    path('categories/', category, name='category'),
    path('category/<int:category_id>/', category_detail, name='category_detail'),
    path('subject/', subject, name='subject'),
    path('subject/<int:subject_id>/', subject_detail, name='subject_detail'),
    path('task/<int:task_id>/', task_detail, name='task_detail'),
    path('search/', search_results, name='search'),
    path('toggle_like/<int:task_id>/', like_toggle, name='toggle_like'),
    path('load_more_comments/<int:task_id>/', load_more_comments, name='load_more_comments'),
    path('profile/<str:username>/', user_profile, name='profile'),
    path('task/create/', create_task, name='create_task'),
    path('task/edit/<int:task_id>/', edit_task, name='edit_task'),
    path('delete/<int:task_id>/', delete_task, name='delete_task'),
]

educator/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/',
         views.SignUp.as_view(
             template_name='users/signup.html'),
         name='signup'
         ),
    path('password_reset/',
         PasswordResetView.as_view(
             template_name='users/password_reset_form.html'),
         name='password_reset_form'
         ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done',
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm',
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete',
    ),
    path(
        'logout/',
        LogoutView.as_view(
            template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(
            template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change_form'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
]

educator/task/forms.py
from django import forms
from .models import *


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'code', 'category', 'subject']


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
        }

educator/task/views.py
import random

from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from django.views.decorators.http import require_POST
from django.utils.text import slugify
from django.http import JsonResponse, HttpResponseForbidden
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

from task.models import *
from task.forms import *

MENU = [{'title': 'О сайте', 'url_name': 'about'},
        {'title': 'Добавить статью', 'url_name': 'add_page'},
        {'title': 'Обратная связь', 'url_name': 'contact'},
        {'title': 'Войти', 'url_name': 'login'},
        ]
NUMBER_OF_CARDS = 9


def index(request):
    random_number = random.randint(1, 100000)
    tasks = Task.objects.all()
    categories = Category.objects.all()
    subjects = Subject.objects.all()
    paginator = Paginator(tasks, NUMBER_OF_CARDS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'title': 'Главная страница',
        'menu': MENU,
        'categories': categories,
        'subjects': subjects,
        'category_selected': 0,
        'random_number': random_number,
    }
    return render(request, 'task/index.html', context=context)


def category(request):
    task = Task.objects.all()
    categories = Category.objects.all()
    subjects = Subject.objects.all()
    paginator = Paginator(categories, NUMBER_OF_CARDS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'title': 'Главная страница',
        'menu': MENU,
        'task': task,
        'page_obj': page_obj,
        'subjects': subjects,
        'category_selected': 0,
    }
    return render(request, 'task/category.html', context)


def category_detail(request, category_id):
    categories = Category.objects.all()
    category = get_object_or_404(Category, id=category_id)
    category_subject = Subject.objects.filter(category=category)
    subjects = Subject.objects.all()
    paginator = Paginator(category_subject, NUMBER_OF_CARDS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'title': 'Детали категории',
        'categories': categories,
        'menu': MENU,
        'category': category,
        'page_obj': page_obj,
        'subjects': subjects,
    }
    return render(request, 'task/category_detail.html', context=context)


def subject(request):
    task = Task.objects.all()
    categories = Category.objects.all()
    subjects = Subject.objects.all()
    paginator = Paginator(subjects, NUMBER_OF_CARDS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'title': 'Главная страница',
        'menu': MENU,
        'task': task,
        'categories': categories,
        'page_obj': page_obj,
        'category_selected': 0,
    }
    return render(request, 'task/subject.html', context=context)


def subject_detail(request, subject_id):
    categories = Category.objects.all()
    subjects = Subject.objects.all()
    subject = get_object_or_404(Subject, pk=subject_id)
    tasks = Task.objects.filter(subject=subject_id)
    paginator = Paginator(tasks, NUMBER_OF_CARDS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'title': subject.title,
        'menu': MENU,
        'subject': subject,
        'page_obj': page_obj,
        'categories': categories,
        'subjects': subjects,
    }
    return render(request, 'task/subject_detail.html', context)


def task_detail(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    categories = Category.objects.all()
    subjects = Subject.objects.all()
    images = TaskImage.objects.filter(task=task_id)
    comments = Comment.objects.filter(task=task_id)
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.task = task
            new_comment.user = request.user
            new_comment.save()
            comment_form = CommentForm()
    else:
        comment_form = CommentForm()
    context = {
        'title': 'Главная страница',
        'menu': MENU,
        'task': task,
        'categories': categories,
        'subjects': subjects,
        'category_selected': 0,
        'images': images,
        'comments': comments,
        'comment_form': comment_form
    }
    return render(request, 'task/task_detail.html', context=context)


def search_results(request):
    query = request.GET.get('q')
    if query:
        tasks = Task.objects.filter(
            Q(title__icontains=query) | Q(description__icontains=query)
        )
        categories = Category.objects.filter(title__icontains=query)
        subjects = Subject.objects.filter(title__icontains=query)

        # Create separate lists for each model
        task_results = [{'model_name': 'task', 'object': task} for task in tasks]
        category_results = [{'model_name': 'category', 'object': category} for category in categories]
        subject_results = [{'model_name': 'subject', 'object': subject} for subject in subjects]

        # Combine the lists and sort by model name
        results = task_results + category_results + subject_results
        results.sort(key=lambda x: x['model_name'])

        # Преобразуем запрос в URL-совместимый формат
        slugified_query = slugify(query)
    else:
        results = []
        slugified_query = None
    context = {
        'results': results,
        'slugified_query': slugified_query
    }
    return render(request, 'task/search_results.html', context)


# def toggle_like(request, task_id):
#     task = get_object_or_404(Task, pk=task_id)
#     user = request.user
#
#     if user.is_authenticated:
#         if task.likes.filter(id=user.id).exists():
#             task.likes.remove(user)
#         else:
#             task.likes.add(user)
#
#     return JsonResponse({'likes_count': task.likes.count()})


def load_more_comments(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    comments = Comment.objects.filter(task=task).order_by('-pub_date')[10:]

    data = []
    for comment in comments:
        data.append({
            'author': comment.author.username,
            'text': comment.text,
            'pub_date': comment.pub_date.strftime("%d %B %Y, %H:%M")
        })

    return JsonResponse(data, safe=False)


@login_required
@require_POST
def like_toggle(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    user = request.user
    try:
        like = Like.objects.get(user=user, task=task)
        like.delete()
        liked = False
    except Like.DoesNotExist:
        Like.objects.create(user=user, task=task)
        liked = True
    like_count = task.likes.count()
    return JsonResponse({'liked': liked, 'like_count': like_count})


def user_profile(request, username):
    user = get_object_or_404(User, username=username)
    tasks = Task.objects.filter(author=user)
    # Проверяем, существует ли чат между текущим пользователем и пользователем профиля
    chat = Chat.objects.filter(participants=request.user).filter(participants=user).first()
    if not chat:
        chat = Chat.objects.create()
        chat.participants.add(request.user, user)
    paginator = Paginator(tasks, NUMBER_OF_CARDS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'user': user,
        'page_obj': page_obj,
        'chat': chat,
    }
    return render(request, 'task/profile.html', context)


@login_required
def create_task(request, task_id=None):
    if task_id is not None:
        task = get_object_or_404(Task, pk=task_id)
        if task.author != request.user:
            return HttpResponseForbidden("You don't have permission to edit this task.")
    else:
        task = None

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            task = form.save(commit=False)
            task.author = request.user
            task.save()
            return redirect('task:task_detail', task_id=task.pk)
    else:
        form = TaskForm(instance=task)

    context = {
        'form': form,
        'task': task,
    }
    return render(request, 'task/create_task.html', context)


def edit_task(request, task_id):
    task = get_object_or_404(Task, pk=task_id)

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect('task:task_detail', task_id=task_id)
    else:
        form = TaskForm(instance=task)

    return render(request, 'task/edit_task.html', {'form': form, 'task': task})


def delete_task(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    if request.method == 'POST':
        task.delete()
        return redirect('task:home')

    return render(request, 'task/delete_task.html', {'task': task})


@login_required
def chat_list(request):
    chats = Chat.objects.filter(participants=request.user)
    context = {
        'chats': chats
    }
    return render(request, 'task/chat_list.html', context)


@login_required
def chat_detail(request, chat_id):
    chat = get_object_or_404(Chat, id=chat_id)
    messages = Message.objects.filter(chat=chat)
    form = MessageForm()

    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data['content']
            sender = request.user
            message = Message.objects.create(chat=chat, sender=sender, content=content)

    context = {
        'chat': chat,
        'messages': messages,
        'form': form,
    }

educator/task/templates/task/category.html
{% extends 'task/base.html' %}

{% block title %}
Список категорий
{% endblock title %}

{% block content %}
<div class="container">
    <h1 class="text-center mt-4 mb-4">Все категории</h1>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for category in page_obj %}
        <div class="col-12 col-md-6 col-xl-4 mb-4">
            <div class="card h-100 shadow d-flex align-items-center justify-content-center">
                <div class="card-body text-center">
                    <h5 class="card-title">{{ category.title }}</h5>
                    <p class="card-text">{{ category.description|linebreaks|truncatewords:20 }}</p>
                    <a href="{% url 'task:category_detail' category_id=category.pk %}" class="btn btn-primary read-more-btn">Подробнее</a>
                </div>
            </div>
        </div>
        {% if forloop.counter|divisibleby:3 and not forloop.last %}
    </div>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% endif %}
        {% endfor %}
    </div>
    <div class="row row-cols-1 row-cols-md-3 g-4">
    {% include 'task/includes/paginator.html' %}
    </div>
</div>
{% endblock %}

educator/task/templates/task/category_detail.html
{% extends 'task/base.html' %}

{% block title %}
{{ category.title }}
{% endblock title %}

{% block content %}
<div class="container">
    <h1 class="mt-4 mb-4 text-center">{{ category.title }}</h1>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for subject in page_obj %}
        <div class="col-12 col-md-6 col-xl-4 mb-4">
            <div class="card h-100 shadow">
                <div class="card-body">
                    <h5 class="card-title text-center">{{ subject.title }}</h5>
                    <p class="card-text text-center">{{ subject.description|truncatewords:40 }}</p>
                    <div class="mt-auto">
                        <a href="{% url 'task:subject_detail' subject_id=subject.pk %}" class="btn btn-primary read-more-btn">Подробнее</a>
                    </div>
                </div>
            </div>
        </div>
        {% if forloop.counter|divisibleby:3 and not forloop.last %}
    </div>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% endif %}
        {% endfor %}
    </div>
    {% include 'task/includes/paginator.html' %}
</div>
{% endblock %}

educator/task/templates/task/chat_detail.html
{% extends 'task/base.html' %}

{% block title %}
  Чат {{ chat.id }}
{% endblock title %}

{% block content %}
  <div class="container">
    <h1>{{ chat.name }}</h1>
    <div id="chat-messages"></div>
  </div>
{% endblock content %}

educator/task/templates/task/delete_task.html
{% extends 'task/base.html' %}
{% load static %}
{% block title %}
Подтверждение удаления задачи - {{ task.title }}
{% endblock title %}

{% block content %}
<div class="container mt-4">
    <div class="card shadow">
        <div class="card-body">
            <h4 class="card-title">Вы уверены, что хотите удалить задачу "{{ task.title }}"?</h4>
            <form method="post">
                {% csrf_token %}
                <div class="d-flex">
                    <button type="submit" class="btn btn-primary read-more-btn mx-1">Удалить</button>
                    <a href="{% url 'task:task_detail' task.id %}" class="btn btn-primary read-more-btn mx-1">Отмена</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

educator/task/templates/task/search_results.html
{% extends 'task/base.html' %}

{% block title %}
Результаты поиска
{% endblock title %}

{% block content %}
<div class="container">
    <h1 class="text-center mt-4 mb-4">Результаты поиска</h1>
    {% if results %}
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for result in results %}
        <div class="col-12 col-md-6 col-xl-4 mb-4">
            <div class="card h-100 shadow">
                {% if result.model_name == "task" %}
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title text-center mb-3">{{ result.object.title }}</h5>
                    <p class="card-text mt-2">{{ result.object.description|linebreaks|truncatewords:20 }}.</p>
                    <div class="category-subject-links">
                        <p>Категория: <a href="{% url 'task:category_detail' category_id=result.object.category.pk %}"
                           class="link-dark">{{ result.object.category }}</a></p>
                    </div>
                    <div class="category-subject-links">
                        <p>Тема: <a href="{% url 'task:subject_detail' subject_id=result.object.subject.pk %}" class="link-dark">
                            {{ result.object.subject }}</a></p>
                    </div>
                    <a href="{% url 'task:task_detail' task_id=result.object.pk %}"
                       class="btn btn-primary read-more-btn">Читать целиком</a>
                    <div class="d-flex justify-content-between mt-2">
                        <div class="like-dislike">
                            <button class="like-button" data-task-id="{{ result.object.id }}">
                                <i class="fas fa-thumbs-up"></i>
                            </button>
                            <span class="likes-count">{{ result.object.likes.count }}</span>
                        </div>
                        <div class="like-dislike">
                            <button class="dislike-button" data-task-id="{{ result.object.id }}">
                                <i class="fas fa-thumbs-down"></i>
                            </button>
                            <span class="dislikes-count">{{ result.object.dislikes.count }}</span>
                        </div>
                    </div>
                    <div class="author-date d-flex justify-content-between mt-2">
                        <a href="#" class="author">{{ result.object.author }}</a>
                        <span>{{ result.object.time_update }}</span>
                    </div>
                </div>
                {% elif result.model_name == "category" %}
                <div class="card-body">
                    <h5 class="card-title text-center mb-3">{{ result.object.title }}</h5>
                    <p class="card-text">{{ result.object.description }}</p>
                    <a href="{% url 'task:category_detail' category_id=result.object.pk %}"
                       class="btn btn-primary read-more-btn">Подробнее</a>
                </div>
                {% elif result.model_name == "subject" %}
                <div class="card-body">
                    <h5 class="card-title text-center mb-3">{{ result.object.title }}</h5>
                    <p class="card-text">{{ result.object.description }}</p>
                    <div class="category-subject-links">
                        <p>Категория: <a href="{% url 'task:category_detail' category_id=result.object.category.pk %}"
                                         class="link-dark">{{ result.object.category }}</a></p>
                    </div>
                    <a href="{% url 'task:subject_detail' subject_id=result.object.pk %}"
                       class="btn btn-primary read-more-btn">Подробнее</a>
                </div>
                {% endif %}
            </div>
        </div>
        {% if forloop.counter|divisibleby:3 and not forloop.last %}
    </div>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% endif %}
        {% endfor %}
    </div>
    {% include 'task/includes/paginator.html' %}
    {% else %}
    <p class="text-center">По вашему запросу ничего не найдено.</p>
    {% endif %}
</div>
{% endblock %}

educator/task/templates/task/subject.html
{% extends 'task/base.html' %}

{% block title %}
Список тем
{% endblock title %}

{% block content %}
<div class="container">
    <h1 class="text-center mt-4 mb-4">Все темы</h1>
    <div class="row row-cols-1 row-cols-md-3 g-4 my-1">
        {% for category in page_obj %}
        <div class="col-12 col-md-6 col-xl-4 mb-4">
            <div class="card h-100 shadow d-flex align-items-center justify-content-center">
                <div class="card-body text-center">
                    <h5 class="card-title">{{ category.title }}</h5>
                    <p class="card-text">{{ category.description|linebreaks|truncatewords:20 }}</p>
                    <div class="category-subject-links">
                        <p>Категория: <a href="{% url 'task:category_detail' category_id=category.pk %}"
                                         class="link-dark">
                            {{ category.title }}</a>
                        </p>
                    </div>
                    <a href="{% url 'task:category_detail' category_id=category.pk %}"
                       class="btn btn-primary read-more-btn">Подробнее</a>
                </div>
            </div>
        </div>
        {% if forloop.counter|divisibleby:3 and not forloop.last %}
    </div>
    <div class="row row-cols-1 row-cols-md-3 g-4 my-1">
        {% endif %}
        {% endfor %}
    </div>
    {% include 'task/includes/paginator.html' %}
</div>
{% endblock %}

educator/task/templates/task/task_detail.html
{% extends 'task/base.html' %}
{% load static %}
{% block title %}
{{ task.title }}
{% endblock title %}

{% block content %}
<div class="container mt-4">
    <div class="card shadow">
        <div class="card-body">
            <h4 class="card-title">{{ task.title }}</h4>
            {% if images %}
            <div class="row mt-3">
                <div class="col-md-12">
                    <div id="imageCarousel" class="carousel slide" data-ride="carousel" data-interval="false">
                        <div class="carousel-inner">
                            {% for image in images %}
                            <div class="carousel-item{% if forloop.first %} active{% endif %}">
                                <img src="{{ image.image.url }}" class="d-block w-100" alt="Image">
                            </div>
                            {% endfor %}
                        </div>
                        <a class="carousel-control-prev" href="#imageCarousel" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        </a>
                        <a class="carousel-control-next" href="#imageCarousel" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        </a>
                    </div>
                </div>
            </div>
            {% endif %}
            {% if task.description %}
            <div class="mt-3">
                {{ task.description|safe }}
                <div class="category-subject-links mt-3">
                    <a href="{% url 'task:category_detail' category_id=task.category.pk %}" class="link-dark">
                        {{ task.category }}</a>
                    <a href="{% url 'task:subject_detail' subject_id=task.subject.pk %}" class="link-dark">
                        {{ task.subject }}</a>
                </div>
            </div>
            {% endif %}
            {% if task.code %}
            <div class="mt-4">
                <pre><code class="python">{{ task.code }}</code></pre>
            </div>
            {% endif %}
        </div>
        <div class="card-footer d-flex justify-content-between">
            <div class="text-muted">
                <a href="{% url 'task:profile' username=task.author %}" class="link-dark">Автор: {{ task.author }}</a>
            </div>
            <div class="text-muted">{{ task.time_update }}</div>
            {% if user.is_authenticated and user == task.author %}
            <div class="d-flex">
                <a href="{% url 'task:edit_task' task.id %}"
                   class="btn btn-primary read-more-btn mx-1">Редактировать</a>
                <a href="{% url 'task:delete_task' task.id %}" class="btn btn-primary read-more-btn mx-1">Удалить</a>
            </div>
            {% endif %}
        </div>
        <div class="card-footer">
            <div class="d-flex justify-content-between">
                <div class="like-dislike">
                    <button class="like-button" data-task-id="{{ task.id }}">
                        <i class="far fa-thumbs-up"></i>
                    </button>
                    <span class="likes-count">{{ task.likes.count }}</span>
                </div>
                <!--<div class="like-dislike">
                    <button class="dislike-button" data-task-id="{{ task.id }}">
                        <i class="far fa-thumbs-down"></i>
                    </button>
                    <span class="dislikes-count">{{ task.dislikes.count }}</span>
                </div>-->
            </div>
        </div>
    </div>
    <hr>
    <div class="rounded mt-4 p-3 shadow">
        <h5 class="mb-3">Комментарии:</h5>
        {% for comment in comments|slice:":10" %}
        <div class="container mt-4">
            <div class="card shadow">
                <div class="card-body">
                    <div class="media-body">
                        <h6 class="mt-0">Автор: {{ comment.author.get_full_name }}</h6>
                        <p class="mb-0">{{ comment.text }}</p>
                        <p class="text-muted small">{{ comment.pub_date|date:"d F Y, H:i" }}</p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        <div id="moreCommentsContainer">
            {% if comments|length > 10 %}
            <button class="btn btn-link mt-3" id="loadMoreComments" role="button">
                Загрузить еще комментарии
            </button>
            {% endif %}
        </div>
        <div class="collapse" id="collapseMoreComments">
            <div id="additionalComments">
            </div>
        </div>
    </div>
    <div class="rounded mt-4 p-3 shadow">
        {% if user.is_authenticated %}
        <form id="commentForm" method="post" style="width: 100%;">
            {% csrf_token %}
            {{ comment_form.as_p }}
            <button type="submit" class="btn btn-primary">Добавить комментарий</button>
        </form>
        {% else %}
        <p>Только авторизованные пользователи могут оставлять комментарии.</p>
        <a href="{% url 'users:login' %}" class="btn btn-primary">Войти</a>
        <a href="{% url 'users:signup' %}" class="btn btn-secondary">Зарегистрироваться</a>
        {% endif %}
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const loadMoreButton = document.querySelector("#loadMoreComments");
        const additionalCommentsContainer = document.querySelector("#additionalComments");

        loadMoreButton.addEventListener("click", function () {
            loadMoreButton.style.display = "none";

            fetch("{% url 'task:load_more_comments' task.id %}")
                .then(response => response.json())
                .then(data => {
                    data.forEach(comment => {
                        const commentCard = document.createElement("div");
                        commentCard.className = "container mt-4";
                        commentCard.innerHTML = `
                            <div class="card shadow">
                                <div class="card-body">
                                    <div class="media-body">
                                        <h6 class="mt-0">Автор: ${comment.author}</h6>
                                        <p class="mb-0">${comment.text}</p>
                                        <p class="text-muted small">${comment.pub_date}</p>
                                    </div>
                                </div>
                            </div>
                        `;
                        additionalCommentsContainer.appendChild(commentCard);
                    });

                    if (data.length > 0) {
                        document.querySelector("#collapseMoreComments").classList.add("show");
                    }
                })
                .catch(error => console.error("Error loading more comments:", error));
        });
    });




</script>
{% endblock %}
<style>
.like-button, .dislike-button {
    border: none;
    background: none;
    cursor: pointer;
    font-size: 1.5em; /* Размер иконки */
    color: #000; /* Цвет иконки */
}

.like-button:focus, .dislike-button:focus {
    outline: none;
}
.like-button i, .dislike-button i {
    border: none;
}
</style>