educator/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

educator/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from api.views import TaskViewSet

router = DefaultRouter()
router.register(r'tasks', TaskViewSet, basename='tasks')

urlpatterns = [
    path('', include(router.urls)),
    # path('auth/', include('djoser.urls.authtoken')),
]

educator/educator/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from educator import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task.urls', namespace='task')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('api/', include('api.urls')),
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    path('schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

educator/task/urls.py
from django.urls import path

from task.views import *

app_name = 'task'

urlpatterns = [
    path('', index, name='home'),
    path('categories/', category, name='category'),
    path('category/<int:category_id>/', category_detail, name='category_detail'),
    path('subject/', subject, name='subject'),
    path('subject/<int:subject_id>/', subject_detail, name='subject_detail'),
    path('task/<int:task_id>/', task_detail, name='task_detail'),
    path('search/', search_results, name='search'),
    path('toggle_like/<int:task_id>/', like_toggle, name='toggle_like'),
    path('load_more_comments/<int:task_id>/', load_more_comments, name='load_more_comments'),
    path('profile/<str:username>/', user_profile, name='profile'),
    path('task/create/', create_task, name='create_task'),
    path('task/edit/<int:task_id>/', edit_task, name='edit_task'),
    path('delete/<int:task_id>/', delete_task, name='delete_task'),
]

educator/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

educator/about/templates/about/includes/footer.html
<!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted">
    <!-- Section: Social media -->
    <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
        <!-- Left -->
        <div class="me-5 d-none d-lg-block">
            <span>Get connected with us on social networks:</span>
        </div>
        <!-- Left -->

        <!-- Right -->
        <div>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-facebook-f"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-twitter"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-google"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-instagram"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-linkedin"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-github"></i>
            </a>
        </div>
        <!-- Right -->
    </section>
    <!-- Section: Social media -->

    <!-- Section: Links  -->
    <section class="">
        <div class="container text-center text-md-start mt-5">
            <!-- Grid row -->
            <div class="row mt-3">
                <!-- Grid column -->
                <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                    <!-- Content -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        <i class="fas fa-gem me-3"></i>Kirill Svitsov
                    </h6>
                    <p>
                        This is my pet project to consolidate knowledge of Django.
                    </p>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        Products
                    </h6>
                    <p>
                        <a href="#!" class="text-reset">Python</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Django</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">JS</a>
                    </p>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        Useful links
                    </h6>
                    <p>
                        <a href="#!" class="text-reset">Settings</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Help</a>
                    </p>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
                    <p><i class="fas fa-home me-3"></i> Lisbon, Portugal</p>
                    <p>
                        <i class="fas fa-envelope me-3"></i>
                        info@example.com
                    </p>
                    <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
                    <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
                </div>
                <!-- Grid column -->
            </div>
            <!-- Grid row -->
        </div>
    </section>
    <!-- Section: Links  -->

    <!-- Copyright -->
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
        © {{ year }} Copyright:
        <a class="text-reset fw-bold" href="https://www.linkedin.com/in/kirill-svitsov-706b8025b/">My LinkedIN.com</a>
    </div>
    <!-- Copyright -->
</footer>
<!-- Footer -->

educator/about/templates/about/includes/header.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand neon-link-red" href="{% url 'task:home' %}">Educator</a>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="categoriesDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Категории
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="categoriesDropdown">
                        <li><a class="dropdown-item" href="{% url 'task:category' %}">Все категории</a></li>
                        {% for category in categories %}
                        <li><a class="dropdown-item" href="{% url 'task:category_detail' category_id=category.pk %}">
                            {{ category.title }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="subjectsDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Темы
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="subjectsDropdown">
                        <li><a class="dropdown-item" href="{% url 'task:subject' %}">Все темы</a></li>
                        {% for subject in subjects %}
                        <li><a class="dropdown-item" href="{% url 'task:subject_detail' subject_id=subject.pk %}">
                            {{ subject.title }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link neon-link-green" href="#">Прочее</a>
                </li>
                {% if user.is_superuser %}
                <li class="nav-item">
                    <a class="nav-link neon-link-blue" href="{% url 'admin:index' %}">Админ панель</a>
                </li>
                {% endif %}
                {% with request.resolver_match.view_name as view_name %}
                <li class="nav-item">
                    <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}"
                       href="{% url 'about:author' %}"
                    >
                        Об авторе
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}"
                       href="{% url 'about:tech' %}"
                    >
                        Технологии
                    </a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Для пользователя
                    </a>
                    <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                        <li>
                            <a class="dropdown-item" href="#">
                                Новая запись
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item {% if view_name  == 'users:password_change_form' %}active{% endif %}"
                               href="{% url 'users:password_change_form' %}">
                                Изменить пароль
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item {% if view_name  == 'users:logout' %}active{% endif %}"
                               href="{% url 'users:logout' %}">
                                Выйти
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if view_name  == 'task:profile' %}active{% endif %}"
                       href="{% url 'task:profile' user %}"
                    >
                        Пользователь: {{ user.username }}
                    </a>
                </li>
                {% else %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Для пользователя
                    </a>
                    <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                        <li>
                            <a class="dropdown-item {% if view_name  == 'users:login' %}active{% endif %}"
                               href="{% url 'users:login' %}"
                            >
                                Войти
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item {% if view_name  == 'users:signup' %}active{% endif %}"
                               href="{% url 'users:signup' %}"
                            >
                                Регистрация
                            </a>
                        </li>
                        {% endif %}
                        {% endwith %}
                    </ul>
                    <form class="d-flex" action="{% url 'task:search' %}" method="get">
                        <input class="form-control me-2" type="search" name="q" placeholder="Поиск" aria-label="Поиск">
                        <button class="btn btn-outline-success" type="submit">Поиск</button>
                    </form>
        </div>
    </div>
</nav>